development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://vast-thicket-27871.herokuapp.com/faye"
  secret_token: "something"
  signature_expiration: 86400 # one day
