development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://pure-bayou-59185.herokuapp.com/
  secret_token: "something"
  signature_expiration: 3600 # one hour
